### ISSUE TITLE
function convertDataViews incompatible with dataviewJS file.link 

### ISSUE THREAD

**Issue by jonathanhung** [oleeskild/obsidian-digital-garden#446]
Using this code in obsidian:

```dataviewjs
	const posts = dv.pages('"200 Posts"');
	dv.list(posts.file.link);
```

The div.innerHTML returned by convertDataView is an empty list (seen in obsidian console) 

> <div><ul class="dataview list-view-ul"><li><span></span></li><li><span></span></li><li><span></span></li><li><span></span></li></ul></div>

Expected (seen in Obsidian)
<img width="692" alt="image" src="https://github.com/oleeskild/obsidian-digital-garden/assets/885187/c4f42a3b-e060-41f7-8060-3f18ea19eb8a">

Conclusion: using file.link works in obsidian but not with digital garden?

**Comment by oleeskild** [comment]
Could be related to #254

**Comment by oleeskild** [comment]
This should have been fixed in the latest release. Please let me know if updating to the latest version fixes it for you

**Comment by jonathanhung** [comment]
✅ updated to 2.51 and dv.list renders correctly in digital garden

**Comment by jonathanhung** [comment]
updated to 2.51.0 but still not getting desired behavior. 

Here are the three queries
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/885187/fe5ab903-7c4a-457f-bb4e-bbf5bd72d5fc)

Here's the render in the digital garden:
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/885187/d66275b1-d128-4b08-966a-fea9924cd7c7)

They are rendering (both in Obsidian and Digital Garden), but I don't think eleventy or markdownit is converting the links that come from dataviewJS. 

![image](https://github.com/oleeskild/obsidian-digital-garden/assets/885187/c622cf61-680b-49ec-8964-8f6bfe304a2e)

You can see in this final image that a class name `block-language-dataview` is added to the <ul> when using DV, but when using DVJS it gets just `dataview`

I'm guessing there's a missing `slugify` arg somewhere in markdownit or eleventy. Or the logic doesn't have the right conditional to locate ul.dataview

**Comment by jonathanhung** [comment]
Co-Pilot wants me to include a filter in the nunjucks template to slugify the URLs. it suggests something like this:

```

     {% set modifiedContent = content | replace(/href="(.+?)"/, 'href="/$1/"') | replace('.md"', '/') | replace(' ', '-') | replace("'", '') | replace('"/', '/"') | lower %}
      {{ modifiedContent | hideDataview | link | taggify | safe}}
      
      ```
      
 However eleventy errors on the delimiting `/`; I don't know regex well enough but will edit this comment if i can figure it out.

**Comment by jonathanhung** [comment]
Also worth sharing that when you use dataviewJS function dv.markdownList it still outputs markup not markdown. 

![image](https://github.com/oleeskild/obsidian-digital-garden/assets/885187/7e67f92c-fd2d-498c-b067-6db1945d0abb)
![image](https://github.com/oleeskild/obsidian-digital-garden/assets/885187/4d3027a1-35b5-431d-977e-52087d407916)

Presently trying to amend the `link` filter in eleventyconfig to find those urls and slugify them. or to create a new filter

**Comment by oleeskild** [comment]
Yep, you are right @jonathanhung, the links from dataviewJs is not working. It's due to the plugin not handling rewriting html links, it only handles markdown links. I'm currently tracking this issue on #346

**Comment by oleeskild** [comment]
This has now been fixed in the latest version of the template. Updating the template should result in all dataviewjs links behave similar to other links.
