### ISSUE TITLE
[Feature Request] SVG Support

### ISSUE THREAD

**Issue by ThatOtherAndrew** [oleeskild/obsidian-digital-garden#88]
Currently, transcluded bitmap images appear to work fine when publishing, however SVG images do not. Having support for this would be incredibly helpful if possible.

**Comment by oleeskild** [comment]
SVG should work, by using the normal ![[filename.svg]] syntax. Do you have an example of this not working?

**Comment by ThatOtherAndrew** [comment]
(notes.thatother.dev/physics/magnetic-fields)[https://notes.thatother.dev/physics/magnetic-fields/] has an example if this not working - I've also attached screenshots below to demonstrate the difference.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/26030336/200337931-80d92e29-075a-4490-bba4-5bd673603a96.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/26030336/200338048-5fa115cd-c72b-46b7-9dbc-b92d3ea9d170.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/26030336/200338104-fe02cbb2-ca9d-4551-b9c6-b0e694a9ea2e.png">

**Comment by oleeskild** [comment]
Ah, right. So this is an excalidraw.svg file. That is currently not supported. How was that file created? Normally an excalidrawing is an .md file. Is there an option in excalidraw to save the image as an svg or something?

**Comment by oleeskild** [comment]
I've looked into this @ThatOtherAndrew , and it is working for me. I used the "Save as SVG into Vault" option in Excalidraw, and used the ![[name of file.excalidraw.svg]] syntax. 

I've just released version 2.25.1 that handles the image width syntax for svgs (`![[name.excalidraw.svg|400`). Maybe that had some side effects that I haven't thought of, and thats why it's working for me now. Could you perhaps try again, and see if it works for you as well with the latest version?

**Comment by ThatOtherAndrew** [comment]
@oleeskild I've tried again, and it still seems to be acting up for me. I am still witnessing [this behaviour](https://github.com/oleeskild/obsidian-digital-garden/issues/88#issuecomment-1305717291), and the issue is resolved when using PNGs instead of SVGs.

**Comment by oleeskild** [comment]
@ThatOtherAndrew Looking at the file in [your repo](https://github.com/ThatOtherAndrew/obsidian-digital-garden/blob/main/src/site/notes/School/S5/Physics/2.%20Particles%20and%20Waves/Magnetic%20Fields.md) there is something weird going on. You may have enabled some sort of compression or something. When the plugin finds an embedded SVG, it simply reads the file and inserts the content into the note file pushed to github.  

Looking at your note, it seems like the svg file, isn't really an SVG but a style tag defining a font. Could you perhaps open the SVG file you have embedded in a text editor, and post the content?

**Comment by ThatOtherAndrew** [comment]
The contents are available at [hatebin.com/qktwezbtif](https://hatebin.com/qktwezbtif). The contents look a bit funny, however my browser is able to read the SVG just fine.

After having a dig in Excalidraw settings, I've noticed some compression settings which may be relevant. I'll try turning off everything compression-related and report back here.

**Comment by ThatOtherAndrew** [comment]
Update: It appears the compression setting is for `.excalidraw.md` files only, and does not affect exported SVGs. I have no idea why my exported file is encoded so strangely.

**Comment by pawelel** [comment]
Noticed that different svg files might behave differently and not all of them can be applied to netlify. Based on my experience with favicon change issues - I had to flatten image to get rid of the issue: 
```bash
12:54:16 AM: > web@1.0.0 build:eleventy
12:54:16 AM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
12:54:17 AM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
12:54:17 AM: [11ty] 1. Having trouble rendering njk template ./src/site/index.njk (via TemplateContentRenderError)
12:54:17 AM: [11ty] 2. (./src/site/index.njk)
12:54:17 AM: [11ty]   Template render error: (/opt/build/repo/src/site/_includes/components/pageheader.njk)
12:54:17 AM: [11ty]   EleventyShortcodeError: Error with Nunjucks shortcode `favicon` (via Template render error)
12:54:17 AM: [11ty] 3. Expected number between 1 and 100000 for density but received 0.8787185354691076 of type number (via Template render error)
12:54:17 AM: [11ty]
12:54:17 AM: [11ty] Original error stack trace: Error: Expected number between 1 and 100000 for density but received 0.8787185354691076 of type number
12:54:17 AM: [11ty]     at Object.invalidParameterError (/opt/build/repo/node_modules/sharp/lib/is.js:124:10)
12:54:17 AM: [11ty]     at Sharp._createInputDescriptor (/opt/build/repo/node_modules/sharp/lib/input.js:80:18)
12:54:17 AM: [11ty]     at new Sharp (/opt/build/repo/node_modules/sharp/lib/constructor.js:298:29)
12:54:17 AM: [11ty]     at Sharp (/opt/build/repo/node_modules/sharp/lib/constructor.js:137:12)
12:54:17 AM: [11ty]     at /opt/build/repo/node_modules/eleventy-favicon/.eleventy.js:14:7
12:54:17 AM: [11ty]     at Array.map (<anonymous>)
12:54:17 AM: [11ty]     at generateIcoFavicon (/opt/build/repo/node_modules/eleventy-favicon/.eleventy.js:13:23)
12:54:17 AM: [11ty]     at /opt/build/repo/node_modules/eleventy-favicon/.eleventy.js:55:9
12:54:17 AM: [11ty]     at Array.forEach (<anonymous>)
12:54:17 AM: [11ty]     at Object.<anonymous> (/opt/build/repo/node_modules/eleventy-favicon/.eleventy.js:54:20)
12:54:18 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:54:17 AM: [11ty] Benchmark    289ms  32%     1× (Data) `./src/site/_data/meta.js`
12:54:17 AM: [11ty] Wrote 0 files in 0.63 seconds (v1.0.2)
12:54:17 AM: ERROR: "build:eleventy" exited with 1.
12:54:17 AM: ​
12:54:17 AM:   "build.command" failed                                        
12:54:17 AM: ────────────────────────────────────────────────────────────────
12:54:17 AM: ​
12:54:17 AM:   Error message
12:54:17 AM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
```
The svg wasn't uploaded and that caused build fail every time I wanted to change favicon until cleaning up the file with free online svg tool.

**Comment by uroybd** [comment]
Ideally, #186 should fix this since transcluded images will be uploaded and referred to instead of embedded.

**Comment by ThatOtherAndrew** [comment]
> Ideally, #186 should fix this since transcluded images will be uploaded and referred to instead of embedded.

@uroybd Just checked, and the issue still persists. I tried using an Excalidraw-exported SVG again and it resulted in the page breaking as shown below:
<img width="1280" alt="image" src="https://github.com/oleeskild/obsidian-digital-garden/assets/26030336/038decc4-fcd4-4a0e-8d51-ffa9870b43d2">

**Comment by uroybd** [comment]
> > Ideally, #186 should fix this since transcluded images will be uploaded and referred to instead of embedded.
> 
> @uroybd Just checked, and the issue still persists. I tried using an Excalidraw-exported SVG again and it resulted in the page breaking as shown below:
> <img width="1280" alt="image" src="https://github.com/oleeskild/obsidian-digital-garden/assets/26030336/038decc4-fcd4-4a0e-8d51-ffa9870b43d2">
> 

Please provide a sample file.

**Comment by ThatOtherAndrew** [comment]
@uroybd Sure thing - here's the page, original Excalidraw file and exported SVG:

[General Relativity.md](https://github.com/oleeskild/obsidian-digital-garden/files/13058203/General.Relativity.md)
[General Relativity_2.excalidraw.md](https://github.com/oleeskild/obsidian-digital-garden/files/13058212/General.Relativity_2.excalidraw.md)
![General Relativity_2 excalidraw](https://github.com/oleeskild/obsidian-digital-garden/assets/26030336/93fd0b31-d4f7-43bc-a6aa-4d545fd7d1bd)

**Comment by uroybd** [comment]
It seems like the linked files are png, not svg. Am I missing something?

**Comment by ThatOtherAndrew** [comment]
Sorry, I had changed the link back to fix my site in the meantime, and forgot about that when uploading the sample file. The issue occurs when any of the links are changed to SVG instead of PNG - here's the corrected file.
[General Relativity.md](https://github.com/oleeskild/obsidian-digital-garden/files/13060966/General.Relativity.md)

**Comment by uroybd** [comment]
Hm, I see. We're still inlining the SVG. @oleeskild we can just upload them like other images, can't we?
